<div class="max-w-4xl mx-auto bg-white dark:bg-gray-800 shadow-2xl rounded-xl p-6 sm:p-10 transition-colors duration-300">
    <header class="pb-6 border-b border-gray-200 dark:border-gray-700 mb-6">
        <h1 class="text-3xl sm:text-3xl font-extrabold text-indigo-600 dark:text-indigo-400 mb-2">
            How It Works: A Star Citizen Killboard Guide
        </h1>
        <p class="text-gray-600 dark:text-gray-400 text-lg">
            Follow these simple steps to locate and upload your Star Citizen <span class="font-semibold text-indigo-500 dark:text-indigo-300">Game.log</span> file to track your in-game activity.
        </p>
    </header>

    <section class="mb-8">
        <h2 class="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-3 flex items-center">
            <span class="text-indigo-500 dark:text-indigo-400 mr-3 text-3xl font-extrabold">1.</span> Locate Your Game.log
        </h2>
        <div class="space-y-4 text-gray-700 dark:text-gray-300">
            <p>The <code class="file-path">Game.log</code> file is generated by Star Citizen every time you play. It's crucial for gathering killboard data and statistics.</p>
            <p>Navigate to your Star Citizen installation folder. The file is typically found in the <span class="font-medium text-indigo-500 dark:text-indigo-300">LIVE</span> directory. The full path is usually similar to this:</p>

            <p class="text-lg font-mono p-3 bg-gray-50 dark:bg-gray-900 rounded-lg shadow-inner overflow-x-auto text-yellow-600 dark:text-yellow-400">
                C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Game.log
            </p>

            <p>Ensure you upload the **most recent** log file, which will contain your latest session data.</p>
            <p class="font-semibold text-green-600 dark:text-green-400">
                Sometimes, your session might be interrupted due to unforeseen circumstances (yeah, the game's full of bugs). Fret not, you can find the log files for your previous sessions here:
            </p>
            <p class="text-lg font-mono p-3 bg-gray-50 dark:bg-gray-900 rounded-lg shadow-inner overflow-x-auto text-yellow-600 dark:text-yellow-400">
                C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\LogBackups\
            </p>
            <p>Simply choose the "list" display option, then sort the directory by the file creation date and upload the logs to the killboard.</p>
        </div>
    </section>

    <div class="border-t border-gray-200 dark:border-gray-700 my-6"></div>

    <section class="mb-8">
        <h2 class="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-3 flex items-center">
            <span class="text-indigo-500 dark:text-indigo-400 mr-3 text-3xl font-extrabold">2.</span> Log In to the Website
        </h2>
        <div class="space-y-4 text-gray-700 dark:text-gray-300">
            <p>Our website uses **Discord** for secure user authentication. You must be logged in to access the uploader page.</p>
            <ol class="list-decimal list-inside space-y-2 ml-4">
                <li>Look for the **Login** button in the top navigation bar. If you see the **Guest** icon, click it to expand the menu.</li>
                <li>Click the **Login with Discord** option.</li>
                <li>You will be redirected to Discord. Authorize our application to access your **Discord Nickname, Global Name, and Email Address**. (We only store this minimal information for login purposes.)</li>
                <li>Once authorized, you will be redirected back to the website and securely logged in.</li>
            </ol>
        </div>
    </section>

    <div class="border-t border-gray-200 dark:border-gray-700 my-6"></div>

    <section class="mb-8">
        <h2 class="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-3 flex items-center">
            <span class="text-indigo-500 dark:text-indigo-400 mr-3 text-3xl font-extrabold">3.</span> Verify your RSI Account
        </h2>
        <div class="space-y-4 text-gray-700 dark:text-gray-300">
            <p>After successfully logging in, the **"Account Verification"** link will appear in your main navigation bar. Click this link and follow instructions on the page to verify your RSI account.</p>
            <p class="text-sm italic text-gray-500 dark:text-gray-400">
                Tip: This page may also be accessible via a link in your user profile dropdown.
            </p>
        </div>
    </section>

    <section class="mb-8">
        <h2 class="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-3 flex items-center">
            <span class="text-indigo-500 dark:text-indigo-400 mr-3 text-3xl font-extrabold">4.</span> Access the Upload Tool
        </h2>
        <div class="space-y-4 text-gray-700 dark:text-gray-300">
            <p>After successfully verifying your RSI account, the **"Upload Game Log"** link will appear in your main navigation bar. Click this link to go to the game log submission form.</p>
            <p class="text-sm italic text-gray-500 dark:text-gray-400">
                Tip: This page may also be accessible via a link in your user profile dropdown.
            </p>
        </div>
    </section>

    <div class="border-t border-gray-200 dark:border-gray-700 my-6"></div>

    <section>
        <h2 class="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-3 flex items-center">
            <span class="text-indigo-500 dark:text-indigo-400 mr-3 text-3xl font-extrabold">5.</span> Submit Your Log
        </h2>
        <div class="space-y-4 text-gray-700 dark:text-gray-300">
            <p>On the upload page, you will find a file input field. Follow these final steps:</p>
            <ol class="list-decimal list-inside space-y-2 ml-4">
                <li>Click the **"Choose File"** button (or similar browser prompt).</li>
                <li>Navigate to the file path found in Step 1 and select the <code class="file-path">Game.log</code> file.</li>
                <li>Once the file name appears next to the button, click the final **"Process Game Log"** button to submit the data for processing.</li>
            </ol>
            <p class="font-semibold text-green-600 dark:text-green-400">
                A success message will confirm your log has been queued! Your kills and events will appear on the kill feed shortly after processing.
            </p>
        </div>
    </section>
</div>
